ToDoListApp2/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoListApp2.Models;

namespace ToDoListApp2.Controllers
{
    public class TaskController : Controller
    {
        // GET: Index
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        // GET: List
        public ActionResult List()
        {
            using (var database = new ApplicationDbContext())
            {
                var tasks = database.Tasks
                    .Include(a => a.Author)
                    .ToList();

                return View(tasks);
            }
        }

        // GET: Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Create

        [HttpPost]
        public ActionResult Create(TaskTodo task)
        {
            if (ModelState.IsValid)
            {
                using (var database = new ApplicationDbContext())
                {
                    var authorId = database.Users
                        .Where(u => u.UserName == this.User.Identity.Name)
                        .First()
                        .Id;

                    task.DueDate = DateTime.ParseExact(task.DueDateString, "dd MMMM yyyy - HH:mm", CultureInfo.InvariantCulture);
                    task.AuthorId = authorId;
                    database.Tasks.Add(task);
                    database.SaveChanges();
                    //return RedirectToAction("Create");
                }
            }
            return RedirectToAction("List");
        }
    }
}

ToDoListApp2/Views/Task/Create.cshtml
@model ToDoListApp2.Models.TaskTodo
@{
    ViewBag.Title = "Create";
}


<div class="container">
    <div class="well">
        <h2>Create Article</h2>
        @using (Html.BeginForm("Create", "Task", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                <label for="dtp_input1" class="col-md-2 control-label">DateTime Picking</label>
                <div class="input-group date form_datetime col-md-5" data-date="1979-09-16T05:25:07Z" data-date-format="dd MM yyyy - HH:mm" data-link-field="dtp_input1">
                    <input class="form-control" size="16" type="text" id="DueDateString" name="DueDateString" value="" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                </div>
                <input type="hidden" id="dtp_input1" value="" /><br />
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "List", "Task", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

@section Styles
{
 
<link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" media="screen">
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">    
}

@section Scripts
{

<script type="text/javascript" src="~/Scripts/bootsrap-datetimepicker.fr.js" charset="UTF-8"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js" charset="UTF-8"></script>

<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0,
        showMeridian: 1
    });
</script>
}

ToDoListApp2/Views/Task/List.cshtml
@model List<ToDoListApp2.Models.TaskTodo>
@{
    ViewBag.Title = "List";
}

<h2>List</h2>
    <ul>
@foreach (var task in Model)
{
    if ((task.DueDate - DateTime.Now).TotalDays < 5)
    {
        <li>@task.Content - Coming soon!</li>
    }
}
</ul>